data:
  - extra_metadata:
      platform: vllm-x4
      GPU: H100
      GPU_count: 4
    files:
      - input/benchmarks-vllm-x4-merged.json
  - extra_metadata:
      platform: llmd-x4
      GPU: H100
      GPU_count: 4
    files:
      - input/benchmarks-llmd-x4-merged.json
options:
  color: platform
  axis_mode: concurrency