data:
  - extra_metadata:
      platform: 1xvllm
      GPU: H100
      GPU_count: 1
    files:
      - input/benchmark-1xvllm.json
  - extra_metadata:
      platform: 2xvllm
      GPU: H100
      GPU_count: 1
    files:
      - input/benchmark-2xvllm.json
options:
  color: platform
  axis_mode: concurrency